export const SET_AUTH_STATE = 'SET_AUTH_STATE'
export const SET_AUTH_DATA = 'SET_AUTH_DATA'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'

export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE'

export const UPDATE_INVENTORY = 'UPDATE_INVENTORY'

export const ALL_CATEGORY_SUCCESS= 'ALL_CATEGORY_SUCCESS'
export const FEATURED_LISTS = 'FEATURED_LISTS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_CART_NO_STOCK = 'UPDATE_CART_NO_STOCK'
export const INCREMENT_CART_QUANTITY = 'INCREMENT_CART_QUANTITY'
export const DECREMENT_CART_QUANTITY = 'DECREMENT_CART_QUANTITY'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const LIST_ORDER_SUCCESS = 'LIST_ORDER_SUCCESS'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'