/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:b83ad73d-e7b6-49c5-8135-90b3dd809481",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_VEungkAXY",
    "aws_user_pools_web_client_id": "5981ek4kpm5g5elq5dplp2r9a4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mmyfci43bnbhbcbpz5wz4ovo3a.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hwyt77j25jfffku5lnivn734s4",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://nxm5xzghva.execute-api.ap-south-1.amazonaws.com/prod",
            "region": "ap-south-1"
        }
    ],
    "aws_user_files_s3_bucket": "kpeccsla899646943534aa39c34c64fd72f84ad82108-prod",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
